### ISSUE TITLE
Extensions gnome-shell à tester / ajouter

### ISSUE THREAD

**Issue by kgaut** [kgaut/CLI-Magic#2]
- [ ] dash to dock
- [x] alternatetab
- [x] clipboard indicator
- [ ] hamster time tracker
- [x] media player indicator
- [ ] taskwarrior integration
- [x] Taskbar
- [x] clipboard indicator
- [ ] open weather
- [ ] lock keys
- [ ] windows list
- [ ] workspace indicator
- [ ] system monitor

**Comment by Chouchen** [comment]
:+1:

**Comment by kgaut** [comment]
ajouts
